export const anonClaimAbi = [
  {
    type: 'function',
    name: 'claim',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'nullifier',      type: 'bytes32'   },
      { name: 'root',           type: 'bytes32'   },
      { name: 'recipient',      type: 'address'   },
      { name: '_domainId',      type: 'uint256'   },
      { name: '_aggregationId', type: 'uint256'   },
      { name: '_leaf',          type: 'bytes32'   },
      { name: '_merklePath',    type: 'bytes32[]' },
      { name: '_leafCount',     type: 'uint256'   },
      { name: '_index',         type: 'uint256'   },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setMerkleRoot',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newRoot', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'merkleRoot',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'scope',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'nullifierUsed',
    stateMutability: 'view',
    inputs: [{ name: 'nullifier', type: 'bytes32' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'error',
    name: 'NullifierSpent',
    inputs: [],
  },
  {
    type: 'error',
    name: 'RootMismatch',
    inputs: [],
  },
  {
    type: 'error',
    name: 'AggregationInvalid',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InsufficientBalance',
    inputs: [],
  },
] as const
