import { NextRequest, NextResponse } from 'next/server'
import fs from 'fs'
import path from 'path'

const KURIER_BASE = process.env.KURIER_API_URL ?? 'https://api-testnet.kurier.xyz/api/v1'
const KURIER_KEY = process.env.KURIER_TESTNET_API_KEY ?? ''
const HORIZEN_CHAIN_ID = 2651420

// Read VK bytes once at module load. Passing the full VK inline avoids needing
// a separate VK-registration step and survives Kurier server resets.
const VK_PATH = path.join(process.cwd(), 'circuit/target/vk/vk')
const VK_HEX = '0x' + fs.readFileSync(VK_PATH).toString('hex')

export async function POST(req: NextRequest) {
  const { proof, publicInputs, vk: browserVk } = await req.json()

  // Prefer the VK generated by bb.js in the browser — it's guaranteed to match
  // the proof byte-for-byte (same WASM function, same ACIR input).
  const vkToUse = browserVk ?? VK_HEX

  console.log('[kurier/submit-proof] proof bytes:', (proof.length - 2) / 2,
    '| publicInputs:', publicInputs.length,
    '| vk bytes:', (vkToUse.length - 2) / 2,
    '| vk source:', browserVk ? 'browser' : 'disk')

  if (browserVk) {
    if (browserVk === VK_HEX) {
      console.log('[kurier/submit-proof] browser VK === disk VK ✓')
    } else {
      console.warn('[kurier/submit-proof] MISMATCH: browser VK differs from disk VK!',
        'disk bytes:', (VK_HEX.length - 2) / 2,
        'browser bytes:', (browserVk.length - 2) / 2)
    }
  }

  console.log('[kurier/submit-proof] publicInputs:', JSON.stringify(publicInputs))

  const kurierPayload = {
    proofType: 'ultrahonk',
    vkRegistered: false,
    chainId: HORIZEN_CHAIN_ID,
    proofOptions: { variant: 'zk', version: 'v0_84' },
    proofData: {
      proof,
      publicSignals: publicInputs,
      vk: vkToUse,
    },
  }

  const res = await fetch(`${KURIER_BASE}/submit-proof/${KURIER_KEY}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(kurierPayload),
  })

  const data = await res.json()
  if (!res.ok) {
    console.error('[kurier/submit-proof] error:', JSON.stringify(data))
  }
  return NextResponse.json(data, { status: res.status })
}
